INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CUSTOMPROCESSING customprocessing)

FIND_PATH(
    CUSTOMPROCESSING_INCLUDE_DIRS
    NAMES customprocessing/api.h
    HINTS $ENV{CUSTOMPROCESSING_DIR}/include
        ${PC_CUSTOMPROCESSING_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CUSTOMPROCESSING_LIBRARIES
    NAMES gnuradio-customprocessing
    HINTS $ENV{CUSTOMPROCESSING_DIR}/lib
        ${PC_CUSTOMPROCESSING_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CUSTOMPROCESSING DEFAULT_MSG CUSTOMPROCESSING_LIBRARIES CUSTOMPROCESSING_INCLUDE_DIRS)
MARK_AS_ADVANCED(CUSTOMPROCESSING_LIBRARIES CUSTOMPROCESSING_INCLUDE_DIRS)

